### PR TITLE
Build libzmq from source, generate SwiftZMQ.framework for macosx and iphoneos platforms.

### PR DESCRIPTION
**Pull request by botero-dev**

### CODE REVIEW

**Comment by paulofaria** [comment]
This is awesome man! Thanks.

**Comment by paulofaria** [comment]
So brew is not required of OSX anymore, right?

**Comment by botero-dev** [comment]
brew is still required for autotools and the building toolchain, but not for running an app with swiftzmq

**Comment by paulofaria** [comment]
I mean this: 

`brew install zeromq --with-libsodium --HEAD`

I should remove from the README, right? The Xcode build phase script builds the lib, doesn't it?

**Comment by botero-dev** [comment]
yes, though the compiled libzmq does not include libsodium

**Comment by paulofaria** [comment]
is it possible to include it?

**Pull request merged**
