### PR TITLE
Add support for Swift 3.0, including the swift package manager

### PR DESCRIPTION
**Pull request by younata**
Maintains iOS support, and the general .xcodeproj so that dynamic frameworks can still be built.

Renames the ZeroMQ C module to CZeroMQ, to be more idiomatic (see https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md), and for the swift package manager, use [my repo](https://github.com/younata/CZeroMQ) to provide CZeroMQ, since SwiftPM REALLY wants a git repo for that external module. 😞

Also removes the declaring parameters as var stuff in Socket.swift, because [SE-0003](https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters.md).

Restructures folder structure to be Sources and Tests, as opposed to SwiftZMQ and SwiftZMQTests, because Swift Package Manager.

### CODE REVIEW

**Comment by paulofaria** [comment]
We already have https://github.com/Zewo/CLibzmq module maps. is it good enough? can you link to it? If not can you please send a PR to it? and maybe add some instructions for linux?

**Comment by younata** [comment]
Whoa hey. Didn't know of that. Thanks, I'll update everything to use CLibzmq.

**Comment by paulofaria** [comment]
I can rename it to CZeroMQ. It seems to be more idiomatic:

> Note we do not call the module CLibjasper. In general, avoid the lib prefix unless the authors of the package typically always refer to it that way. A good rule of thumb is to look at the header files, here we can see the header is called simply "jasper.h". In the event of non-typical headers (eg jpeglib.h) refer to the project homepage, the authors of the JPEG library refer to it as “The JPEG library” and not “libjpeg” or “jpeglib”. Pay attention to capitalization; it is CJPEG and not CJpeg, because JPEG is an acronym and is typically spelled all-caps. It is CJasPer and not CJasper because the project itself refers to the library as “JasPer” in all their documentation.

**Comment by younata** [comment]
Additionally, push a tag to it. The SwiftPM really wants a tag for that major version.

**Comment by paulofaria** [comment]
I just went ahead and renamed it.

**Comment by paulofaria** [comment]
Is it good? give me an OK if I can tag it, or send a PR to make any necessary changes and then I'll tag it. If you could please add instructions for linux installation.

**Comment by younata** [comment]
Tag it once https://github.com/Zewo/CZeroMQ/pull/3 is merged. Thanks!

**Comment by paulofaria** [comment]
merged and tagged

**Pull request merged**
